name: shinchoku
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^3.0.3

  # State Management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.3

  # Firebase
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  firebase_storage: ^10.2.9
  firebase_analytics: ^9.1.2
  firebase_crashlytics: ^2.5.3
  firebase_remote_config: ^2.0.2
  firebase_dynamic_links: ^4.0.8
  firebase_in_app_messaging: ^0.6.0+9
  # Authentication Third Parties
  google_sign_in: ^5.2.4
  twitter_login: ^4.0.1

  # Remote Content
  dio: ^4.0.4

  # Local Content (DB/Prefs)
  flutter_secure_storage: ^5.0.2

  # Utilities
  string_similarity: ^2.0.0
  url_launcher: ^6.0.20
  cron: ^0.4.0
  flutter_local_notifications: ^9.3.3
  geolocator: ^8.2.0
  permission_handler: ^9.2.0

  # UI
  flutter_screenutil: ^5.3.1
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  syncfusion_flutter_datepicker: ^19.4.54
  image_picker: ^0.8.4+10
  flutter_staggered_grid_view: ^0.6.1
  shimmer: ^2.0.0
  rive: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/pics/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
